name: Lint Docs

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check internal links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --exclude-all-private '**/*.md'

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: |
            **/*.md
            !.github/**/*.md
